#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:a100
#SBATCH --job-name=test_vae
#SBATCH -o test_vae.out
conda activate comp3710

python -m src.visualise \
  --data_root /home/groups/comp3710/OASIS \
  --ckpt runs/oasis-vae-128d32/best.pt \
  --size 128
